### ISSUE TITLE
Suggestion: creating a linting package that uses rpmlint to check for common packaging errors in spec files?

### ISSUE THREAD

**Issue by fusion809** [waveclaw/language-rpm-spec#13]
Hi,

I was just wondering if you might be interested in creating a linting package for RPM spec files that would use the `rpmlint` tool to check for common errors.

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
I've made an attempt at it myself, at [fusion809/linter-rpmlint](https://github.com/fusion809/linter-rpmlint), but it doesn't seem to work, not sure why.

**Comment by waveclaw** [comment]
A linter is out of scope of this project which just provides a syntax highlighter, and one with particular issues due to the parsing of sections.

Tools such as rpmlint can catch major problems with specfiles or build rpms.  But most the non-syntax related problems in a package is due to compliance with a particular platform's policies and guidelines.

For instance, the brp-checks from the SUSE project are a suite of scripts and tools ran by the (Open Build Service used by SUSE)[https://build.opensuse.org] to validate a package does what it should.  These have to run after a package is build and after it is installed and again after uninstalling it.

So I could look at doing a linter, but was quite happy with just providing a basic (if not the most well maintained) syntax highlighter for atom editing of RPM specfiles.
