### ISSUE TITLE
Generate new changelog item

### ISSUE THREAD

**Issue by mcepl** [waveclaw/language-rpm-spec#16]
See https://matej.ceplovi.cz/blog/gedit-snippet-generating-rpm-spec-changelog-line.html for the code.

Would it be possible to add this functionality to your plugin, please?

**Comment by waveclaw** [comment]
I can try this but getting some of the information requires arbitrary parsing of the document.  This is not trivial. 

Just checkout the difficulty required for getting the date:

https://github.com/atom/snippets/issues/33

This is a low-value item for uses of Open Build Services since these users often prefer to use dedicated Changelog files instead.

**Comment by waveclaw** [comment]
This requires access to document data and environment information.  That means writing an entire javascript dynamic snippet system, beyond the scope of my intent for this simple language highlighter. 

See 
https://github.com/atom/snippets/pull/173
https://github.com/atom/snippets/issues/181

Patches are more than welcome, but this is a very large new addition at this point.
